### ISSUE TITLE
The url of the sign in process image (the drawing pen image) is down

### ISSUE THREAD

**Issue by illia-kriukov** [illia-kriukov/svs-google-docs-add-on#29]
Important, the url of the sign in process image (the drawing pen image) is down. [http://www.waremakers.com/sites/default/files/pens_fountain_pen_1.png].
![capture](https://cloud.githubusercontent.com/assets/16224847/24837655/4a9e9d8a-1d39-11e7-853c-970a587d7474.PNG)

**Comment by jikalousek** [comment]
I have the image downloaded so once we have our server online we will put the image there and access it from there.

**Comment by illia-kriukov** [comment]
Usualy we should use separate image server for such case, because back-end part should contains only business logic and don't store resources for front-end. As alternative solution, try to put this image in our Add-On project and use it from Google App Script.

**Comment by jikalousek** [comment]
I'm not sure if it's possible. Here https://developers.google.com/apps-script/add-ons/ they say this:

"Most add-ons include a logo or other images. These assets aren't packaged with the add-on; instead, your user interfaces reference them just like any other web page would. You can host assets on your own web server using Firebase Hosting."

I don't think we will set up a new hosting just because of images. I would use the existing back-end server.

**Comment by aperkaz** [comment]
Whe can just change the image, as @illia-kriukov says, i dont think is a good idea to mix in the back end the front end assets and the signatures.
Example: https://www.google.se/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwib5-2ruZzTAhViQJoKHfTwDAsQjBwIBA&url=http%3A%2F%2Fwww.iconarchive.com%2Fdownload%2Fi43140%2Foxygen-icons.org%2Foxygen%2FMimetypes-application-pgp-signature.ico&bvm=bv.152180690,d.ZGg&psig=AFQjCNF_uPQ1BB5ACU8YkhVB27qHguEiJA&ust=1491997778782724
